### ISSUE TITLE
Similarity between image-1 and image-2: 0.9198863419190031

### ISSUE THREAD

**Issue by YOLOPOLO0** [olivierbenard/differences-between-two-images#1]
not showing the images of result how to see the output of differences in images please help

**Comment by olivierbenard** [comment]
Hello,

Could you provide more details? E.g.:
1. Have you installed all the dependencies already?
2. Which OS are you running the script on? 
3. Where the issue stands? The script terminates with an error or you just do not see anything popping up?

To give you more context:

I recently refactor the whole project (haven't touched it since 2 years, somehow your open issue made me jump back on it). Here is a short overview of what I did:

1. I have made the guidelines more explicit (see README.md)
2. refactored the code to make it more understandable
3. I changed the logic by replacing `cv2.imshow()` for `cv2.imwrite()` with the results now being captured under the `results/` folder instead of opening a window on the fly (because it used to work well on Windows but not so well on MacOs).

Therefore, you might want to have a second try because so far, I am not sure exactly where the issue stand from your side.

Kind regards,
OB

**Comment by olivierbenard** [comment]
I am closing the issue. The new release makes it more user-friendly.
